Medical/Areas/Admin/Controllers/AdvertiseAdminController.cs
using Medical.Models;
using Medical.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Medical.Controllers
{
    [Area(areaName:"Admin")]
    public class AdvertiseAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private readonly IWebHostEnvironment _host;
        
        private readonly MedicalContext _medicalContext;
        public AdvertiseAdminController(MedicalContext medicalContext, IWebHostEnvironment hostEnvironment)
        {
            _medicalContext = medicalContext;
            _host = hostEnvironment;
        }
       
        public IActionResult AdstatueCheckBox()
        {
            var data = _medicalContext.AdvertiseStatues.Select(a => a.Adstatue).Distinct();
            return Json(data);
        }
        
        public IActionResult List(AAdvertiseSearchKeywordViewModel vModel)
        {
            List<AAdvertiseViewModel> list = new List<AAdvertiseViewModel>();
            if (string.IsNullOrEmpty(vModel.txtKeyword))
            {
                var data = _medicalContext.Advertises.Include(x => x.Adstatue);
                foreach(var a in data)
                {
                    AAdvertiseViewModel ar = new AAdvertiseViewModel();
                    ar.advertise = a;
                    list.Add(ar);
                }
            }
            else
            {
                var data = _medicalContext.Advertises.Where(a => 
                a.AdTitle.Contains(vModel.txtKeyword)||
                a.AdContant.Contains(vModel.txtKeyword));
                foreach (var a in data)
                {
                    AAdvertiseViewModel ar = new AAdvertiseViewModel();
                    ar.advertise = a;
                    list.Add(ar);
                }
            }

            return View(list.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Advertise ad, AAdvertiseViewModel a)
        {
            if (a.photo != null)
            {
                string path = Path.Combine(_host.WebRootPath, "uploads", a.photo.FileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    a.photo.CopyTo(fileStream);
                    a.AdPicturePath = a.photo.FileName;
                }
            }
            
            ad.AdminId = a.AdminId;
            ad.AdTitle = a.AdTitle;
            ad.Adstatue = a.Adstatue;
            ad.AdContant = a.AdContant;
            ad.AdPicturePath = a.AdPicturePath;

            _medicalContext.Advertises.Add(ad);
            _medicalContext.SaveChanges();
            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {
            Advertise advertise = _medicalContext.Advertises.FirstOrDefault(a => a.No == id);
            if (advertise != null)
            {
                _medicalContext.Advertises.Remove(advertise);
                _medicalContext.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            AAdvertiseViewModel ad = new AAdvertiseViewModel();
            ad.advertise = _medicalContext.Advertises.Include(x=>x.Adstatue).FirstOrDefault(a => a.No == id);
            if (ad == null)
            {
                return RedirectToAction("List");
            }
            return View(ad);
        }
        [HttpPost]
        public IActionResult Edit(AAdvertiseViewModel a)
        {
            Advertise ad = _medicalContext.Advertises.FirstOrDefault(t => t.No == a.No);
            if (ad != null)
            {
                if (a.photo != null)
                {
                    //string aName = Guid.NewGuid().ToString() + ".jpg";
                    string path = Path.Combine(_host.WebRootPath, "uploads", a.photo.FileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        a.photo.CopyTo(fileStream);
                        a.AdPicturePath = a.photo.FileName;
                    }
                }
                ad.AdminId = a.AdminId;
                ad.AdTitle = a.AdTitle;
                ad.Adstatue = a.Adstatue;
                ad.AdContant = a.AdContant;
                ad.AdPicturePath = a.AdPicturePath;
                _medicalContext.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

Medical/Areas/Admin/Views/AdvertiseAdmin/Create.cshtml
@model Medical.ViewModel.AAdvertiseViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}

@section Styles{

    @*修改*@
    <style>

        .card {
            margin-left: 20px;
        }

            .card div {
                margin-left: 20px;
            }

        .form-group select {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group .form-control {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group textarea {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group label {
            font-size: 20px;
            font-family: 微軟正黑體;
            font-weight: bold;
        }

        #selDoctorName option {
            font-size: 20px;
            font-family: 微軟正黑體;
            font-weight: bold;
        }
    </style>
}



<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            @*修改*@
            <h1 style="font-family: 微軟正黑體;font-weight:bold;margin-left:100px">新增廣告(Create)</h1>
        </div>
    </div>
</div>



@*修改*@
<div class="card" style="padding-top:30px">

    @*修改*@
    <div class="col-md-5">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="No" class="form-control" />
                <span asp-validation-for="No" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdminId" class="control-label" hidden="hidden"></label>
                <input asp-for="AdminId" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="AdTitle" class="control-label"></label>
                <input asp-for="AdTitle" class="form-control" />
                <span asp-validation-for="AdTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdContant" class="control-label"></label>
                <textarea id="editor" asp-for="AdContant" class="form-control" style="width:500px;height:200px;font-size:15px"></textarea>
                <span asp-validation-for="AdContant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdPicturePath" class="control-label"></label>
                <input name="photo" type="file" asp-for="AdPicturePath" class="form-control" />

            </div>
            <div class="form-group">
                @*修改*@
                <label asp-for="Adstatue.Adstatue" class="control-label">狀態</label>
                <select asp-for="Adstatue.Adstatue" class="form-control form-control-lg " id="selAdstatue"></select>
                <span asp-validation-for="Adstatue.Adstatue" class="text-danger"></span>
            </div>
            @*修改*@
            <div class="form-group btn btn-success">
                <i class="fas fa-plus">
                    <input type="submit" value="新增" class="btn btn-success" onclick="return confirm('確定新增此資料嗎??')" style="width:40px;height:30px;margin:0;padding:0;font-weight:bold;" />
                </i>
            </div>
        </form>
    </div>
    @*修改*@
    <div style="margin: 0 0 50px 45px">
        <a asp-action="List" type="button" class="btn bg-gradient-warning" style="border-radius: 5px; font-weight: bold"><i class="fa fa-book" style="margin-right: 10px;"></i>回到廣告內容</a>
    </div>
</div>





@section Scripts {
    <script>
        //增加文章內容的格式轉換
        ClassicEditor
            .create(document.querySelector('#editor'));


    LoadAdstatue();

    async function LoadAdstatue() {
        const response = await fetch("@Url.Content("~/Admin/advertiseAdmin/AdstatueCheckBox")")
        const datas = await response.json();
        datas.forEach(value => {
            const option = new Option(value, value);
            let selAdstatue = document.querySelector("#selAdstatue");
            selAdstatue.options.add(option);
        })
    }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medical/Areas/Admin/Views/AdvertiseAdmin/Edit.cshtml
@model Medical.ViewModel.AAdvertiseViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}

@section Styles{

    @*修改*@
    <style>

        .card {
            margin-left: 20px;
        }

            .card div {
                margin-left: 20px;
            }

        .form-group select {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group .form-control {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group textarea {
            border: 2px solid gold;
            border-radius: 10px;
        }

        .form-group label {
            font-size: 20px;
            font-family: 微軟正黑體;
            font-weight: bold;
        }

        #selDoctorName option {
            font-size: 20px;
            font-family: 微軟正黑體;
            font-weight: bold;
        }
    </style>
}


<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 style="font-family: 微軟正黑體;font-weight:bold;margin-left:100px">修改廣告(Create)</h1>
        </div>
    </div>
</div>

<div class="card" style="padding-top:30px">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Edit" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" name="No" asp-for="No" />
                <div class="form-group">
                    <label asp-for="AdminId" class="control-label" hidden="hidden"></label>
                    <input asp-for="AdminId" class="form-control" type="hidden" />
                    <span asp-validation-for="AdminId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdTitle" class="control-label"></label>
                    <input asp-for="AdTitle" class="form-control" />
                    <span asp-validation-for="AdTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdContant" class="control-label"></label>
                    <textarea id="editor" asp-for="AdContant" class="form-control card-header" style="width:500px;height:200px;font-size:15px"></textarea>
                    <span asp-validation-for="AdContant" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdPicturePath" class="control-label"></label>
                    <input type="file" name="photo" asp-for="AdPicturePath" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Adstatue.Adstatue" class="control-label">狀態</label>
                    <select asp-for="Adstatue.Adstatue" class="form-control form-control-lg " id="selAdstatue"></select>
                    <span asp-validation-for="Adstatue.Adstatue" class="text-danger"></span>
                </div>
                <div class="form-group btn btn-success">
                    <i class="fas fa-upload">
                        <input type="submit" value="修改" class="btn btn-success" onclick="return confirm('確定修改此資料嗎??')" style="width:40px;height:30px;margin:0;padding:0;font-weight:bold;" />
                    </i>
                </div>

            </form>
        </div>
    </div>
    <div style="margin: 0 0 50px 65px">
        <a asp-action="List" type="button" class="btn bg-gradient-warning" style="border-radius: 5px; font-weight: bold"><i class="fa fa-book" style="margin-right: 10px;"></i>回到廣告內容</a>
    </div>
</div>




@section Scripts {
    <script>
        //增加文章內容的格式轉換
        ClassicEditor
            .create(document.querySelector('#editor'));


        LoadAdstatue();

    async function LoadAdstatue() {
        const response = await fetch("@Url.Content("~/Admin/advertiseAdmin/AdstatueCheckBox")")
        const datas = await response.json();
        datas.forEach(value => {
            const option = new Option(value, value);
            let selAdstatue = document.querySelector("#selAdstatue");
            selAdstatue.options.add(option);
        })
    }
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medical/Areas/Admin/Views/AdvertiseAdmin/List.cshtml
@model IEnumerable<Medical.ViewModel.AAdvertiseViewModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}



<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 style="font-family: 微軟正黑體; font-weight: bold; color: mediumslateblue;">廣告輪播(後臺系統)</h1>
        </div>
          </div>
</div>


<div class="card">

    @*開始修改*@


    @using (Html.BeginForm())
    {
        <div style="text-align: center;padding-top:20px">
            <label class="" style="font-size: 25px; font-family: 微軟正黑體; font-weight: bold; color: mediumslateblue;">關鍵字 : </label>
            @Html.TextBox("txtKeyword", "", new { @class = "font-weight-bold", style = "font-size:26px;border-radius:15px;", @placeholder = "search..." })
            <button type="submit" class="btn btn-info btn-lg">
                <i class="fa fa-search">
                    查詢
                </i>
            </button>
        </div>
    }
    @*修改*@
    <p style="padding: 20px 30px 0 0; text-align: right;">
        @Html.ActionLink("新增衛教內容", "Create", "AdvertiseAdmin", "",
                               new { @class = "btn btn-outline-success", @style = "font-size:18px;border-radius:5px; font-weight: bold " })
    </p>

    @{
        int count = 0;
        <div class="card">
                <div class="card-header">
                        <h3 class="card-title" style="font-size: 25px; font-family: 微軟正黑體; font-weight: bold; color: mediumslateblue;">廣告表單細節</h3>
                </div>

            <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                                <thead>
                                    <tr>
                                        <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">序</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">標題</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">廣告內容</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">圖片</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">狀態</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        count++;
                                        <tr class="odd">
                                            <td class="dtr-control sorting_1 font-weight-bold" tabindex="0" style="width:5%">@count</td>
                                            <td style="width:10%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.AdTitle)</td>
                                            <td style="width:50%" class="font-weight-bold">
                                                <p>
                                                    @Html.DisplayFor(modelItem => item.AdContant)
                                                </p>
                                            </td>
                                            <td class="font-weight-bold"><img src="~/uploads/@item.AdPicturePath" style="width:150px;height:150px"></td>
                                            <td style="width:8%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.Adstatue.Adstatue)</td>
                                            <td style="width:8%">
                                                <div class="fas fa-pencil-alt" style="color: dodgerblue; margin-block: 3px">
                                                    @Html.ActionLink("修改", "Edit", "AdvertiseAdmin", new { id = item.No }, new { @class = "btn bg-gradient-primary btn-sm" })
                                                </div>
                                                <br />
                                                <div class="fas fa-trash" style="color: orangered; margin-top: 3px">
                                                    @Html.ActionLink("刪除", "Delete", "AdvertiseAdmin", new { id = item.No },
new { onclick = "return confirm('確定要刪除此筆資料嗎??')", @class = "btn btn-danger btn-sm", @style = "margin-left:1px" })
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</div>