Medical/Areas/Admin/Controllers/ArticleAdminController.cs
using Medical.Models;
using Medical.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Medical.Controllers
{
    [Area(areaName: "Admin")]
    public class ArticleAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private readonly MedicalContext _medicalContext;
        public ArticleAdminController(MedicalContext medicalContext)
        {
            _medicalContext = medicalContext;
        }
        

        public IActionResult List(AArticleSearchKeywordViewModel vModel)
        {
            
            List<AArticleViewModel> list = new List<AArticleViewModel>();

            if (string.IsNullOrEmpty(vModel.txtKeyword))
            {
                var datas = _medicalContext.Articles.Include(x => x.Doctor);
                foreach(var a in datas)
                {
                    AArticleViewModel ar = new AArticleViewModel();
                    ar.article = a;
                    list.Add(ar);
                }
            }
            else
            {
                var datas = _medicalContext.Articles.Include(x=>x.Doctor).Where(a => 
                a.Articeltitle.Contains(vModel.txtKeyword)||
                a.Doctor.DoctorName.Contains(vModel.txtKeyword));
                foreach (var a in datas)
                {
                    AArticleViewModel ar = new AArticleViewModel();
                    ar.article = a;
                    list.Add(ar);
                }
            }
            return View(list.ToList());
        }
        public IActionResult CreateDoctorCheckBox()
        {
            var data = _medicalContext.Doctors.Select(x => x.DoctorName).Distinct();
            return Json(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Article a)
        {
            a.CreateDate = DateTime.Now.ToString("yyyy/MM/dd");
            _medicalContext.Articles.Add(a);
            _medicalContext.SaveChanges();
            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {

            Article article = _medicalContext.Articles.FirstOrDefault(a => a.ArticleId == id);
            if (article != null)
            {
                _medicalContext.Articles.Remove(article);
                _medicalContext.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            AArticleViewModel article = new AArticleViewModel();
            article.article = _medicalContext.Articles.Include(x=>x.Doctor).FirstOrDefault(a => a.ArticleId == id);
            if (article == null)
            {
                return RedirectToAction("List");
            }
            return View(article);
        }
        [HttpPost]
        public IActionResult Edit(Article a)
        {
            Article ar = _medicalContext.Articles.FirstOrDefault(t => t.ArticleId == a.ArticleId);
            if (ar != null)
            {
                ar.Doctor= a.Doctor;
                ar.CreateDate = DateTime.Now.ToString("yyyy/MM/dd");
                ar.ArticleContent = a.ArticleContent;
                ar.Articeltitle = a.Articeltitle;
            }
            _medicalContext.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

Medical/Areas/Admin/Views/ArticleAdmin/Create.cshtml
@model Medical.ViewModel.AArticleViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}

@section Styles{ 

@*修改*@
<style>
    
    .card {
        margin-left: 20px ;
        
    }
        .card div {
            margin-left: 20px;
           
        }
        
        
    .form-group select {
        border: 2px solid gold;
        border-radius: 10px;
    }
    .form-group .form-control {
        border: 2px solid gold;
        border-radius: 10px;
    }
    .form-group textarea {
        border: 2px solid gold;
        border-radius: 10px;
        padding-left:20px
    }
    .form-group label{
        font-size:20px;
        font-family:微軟正黑體;
        font-weight:bold;
    }
    #selDoctorName option {
        font-size: 20px;
        font-family: 微軟正黑體;
        font-weight: bold;
    }
</style>
}

        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    @*修改*@
                    <h1 style="font-family: 微軟正黑體;font-weight:bold;margin-left:100px">新增文章(Create)</h1>
                </div>
            </div>
        </div>

@*修改*@       
 <div class="card" style="padding-top:30px">
            <div class="row">
                @*修改*@
                <div class="col-md-5">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group" >
                            @*修改*@
                            <label asp-for="Doctor.DoctorName" class="control-label">醫生</label>
                            <select asp-for="Doctor.DoctorName" class="form-control form-control-lg " id="selDoctorName"></select>
                            <span asp-validation-for="Doctor.DoctorName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Articeltitle" class="control-label"></label>
                            <input asp-for="Articeltitle" class="form-control" />
                            <span asp-validation-for="Articeltitle" class="text-danger"></span>
                        </div>
                        @*修改*@
                        <div class="form-group">
                            <label asp-for="ArticleContent" class="control-label"></label>
                            <textarea id="editor" asp-for="ArticleContent" class="form-control" ></textarea>
                            
                        </div>
                        <div class="form-group">
                            @*修改*@
                            <label asp-for="CreateDate" class="control-label" hidden="hidden"></label>
                            <input asp-for="CreateDate" class="form-control" hidden="hidden" />

                        </div>
                        @*修改*@
                        <div class="form-group btn btn-success" >
                                <i class="fas fa-plus" >
                                    <input type="submit" value="新增" class="btn btn-success" onclick="return confirm('確定新增此資料嗎??')" style="width:40px;height:30px;margin:0;padding:0;font-weight:bold;"/>
                                </i>
                        </div>
                    </form>
                </div>
            </div>
            @*修改*@
            <div style="margin: 0 0 50px 65px">
                <a asp-action="List" type="button" class="btn bg-gradient-warning" style="border-radius: 5px; font-weight: bold"><i class="fa fa-book" style="margin-right: 10px;"></i>回到衛教文章</a>
            </div>

        </div>




@section Scripts {
    <script>
        //增加文章內容的格式轉換
        ClassicEditor
            .create(document.querySelector('#editor'));


        //加入醫生姓名
    LoadDoctorName();

    async function LoadDoctorName() {
        const response = await fetch("@Url.Content("~/admin/ArticleAdmin/CreateDoctorCheckBox")");
        const datas = await response.json();

        datas.forEach(value=> {

            let options = new Option(value, value);
            let selDoctorName = document.querySelector("#selDoctorName");
            selDoctorName.options.add(options);
        })
        }

        //日期驗證
        //let strDate = document.getElementById("str_Date");
        //let spDate = document.getElementById("sp_date");

        //strDate.addEventListener("blur", () => {
        //    var dateArr = strDate.value.split("/");
        //    var dateNow = new Date();
        //    if (strDate.value == "") {
        //        spDate.innerHTML = "<img src='../../img/error.png' />請輸入完整日期!!";
        //    }

        //    else {
        //        let year = dateArr[0];
        //        let month = dateArr[1];
        //        let day = dateArr[2];
        //        if (year <= dateNow.getFullYear()) {
        //            if (month >= 1 && month <= 12) {
        //                //小月
        //                if (month == 4 || month == 6 || month == 9 || month == 11) {
        //                    if (day > 0 && day <= 30) {
        //                        spDate.innerHTML = "<img src = '../../img/correct.jpg' />格式正確"
        //                    }
        //                    else {
        //                        spDate.innerHTML = "<img src='../../img/error.png' />日期有誤，請重新輸入日期"
        //                    }
        //                }
        //                //例外月(2月)
        //                else if (month == 2) {
        //                    //潤月
        //                    if ((year % 4) == 0) {
        //                        if (day > 0 && day <= 29) {
        //                            spDate.innerHTML = "<img src = '../../img/correct.jpg' />格式正確"
        //                        }
        //                        else {
        //                            spDate.innerHTML = "<img src='../../img/error.png' />日期有誤，請重新輸入日期"
        //                        }
        //                    }
        //                    else {
        //                        if (day > 0 && day <= 28) {
        //                            spDate.innerHTML = "<img src = '../../img/correct.jpg' />格式正確"
        //                        }
        //                        else {
        //                            spDate.innerHTML = "<img src='../../img/error.png' />日期有誤，請重新輸入日期"
        //                        }
        //                    }
        //                }
        //                //大月
        //                else {
        //                    if (day > 0 && day <= 31) {
        //                        spDate.innerHTML = "<img src = '../../img/correct.jpg' />格式正確"
        //                    }
        //                    else {
        //                        spDate.innerHTML = "<img src='../../img/error.png' />日期有誤，請重新輸入日期"
        //                    }
        //                }
        //            }
        //            else {
        //                spDate.innerHTML = "<img src='../../img/error.png' />月份有誤，請重新輸入月份";
        //            }
        //        }
        //        else {
        //            spDate.innerHTML = "<img src='../../img/error.png' />年份有誤，請重新輸入年份";
        //        }
        //    }
        //})


    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medical/Areas/Admin/Views/ArticleAdmin/Edit.cshtml
@model Medical.ViewModel.AArticleViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}

<style>

    .card {
        margin-left: 20px;
    }

        .card div {
            margin-left: 20px;
        }

    .form-group select {
        border: 2px solid gold;
        border-radius: 10px;
    }

    .form-group .form-control {
        border: 2px solid gold;
        border-radius: 10px;
    }

    .form-group textarea {
        border: 2px solid gold;
        border-radius: 10px;
    }

    .form-group label {
        font-size: 20px;
        font-family: 微軟正黑體;
        font-weight: bold;
    }

    #selDoctorName option {
        font-size: 20px;
        font-family: 微軟正黑體;
        font-weight: bold;
    }
</style>
}

<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 style="font-family: 微軟正黑體;font-weight:bold;margin-left:100px">修改文章(Edit)</h1>
        </div>
    </div>
</div>

<div class="card" style="padding-top:30px">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ArticleId" class="control-label " hidden="hidden"></label>
                    <input asp-for="ArticleId" class="form-control" type="hidden" />

                </div>
                <div class="form-group">
                    <label asp-for="Doctor.DoctorName" class="control-label">醫生</label>
                    <input asp-for="Doctor.DoctorName" class="form-control" disabled="disabled" />
                    <span asp-validation-for="Doctor.DoctorName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdminId" class="control-label" hidden="hidden"></label>
                    <input asp-for="AdminId" class="form-control" type="hidden" />

                </div>
                <div class="form-group">
                    <label asp-for="Articeltitle" class="control-label"></label>
                    <input asp-for="Articeltitle" class="form-control" />
                    <span asp-validation-for="Articeltitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ArticleContent" class="control-label"></label>
                    <textarea id="editor" asp-for="ArticleContent" class="form-control" style="width:500px;height:200px;font-size:15px"></textarea>
                    <span asp-validation-for="ArticleContent" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreateDate" class="control-label" hidden="hidden"></label>
                    <input asp-for="CreateDate" class="form-control" hidden="hidden" />

                </div>
                <div class="form-group btn btn-primary">
                    <i class="fas fa-upload">
                        <input type="submit" value="修改" class="btn btn-primary" onclick="return confirm('確定修改此資料嗎??')" style="width:40px;height:30px;margin:0;padding:0;font-weight:bold;" />
                    </i>
                </div>

            </form>
        </div>
    </div>

    <div style="margin: 0 0 50px 65px">
        <a asp-action="List" type="button" class="btn bg-gradient-warning" style="border-radius: 5px; font-weight: bold"><i class="fa fa-book" style="margin-right: 10px;"></i>回到衛教文章</a>
    </div>
</div>


@section Scripts {
    <script>
        //增加文章內容的格式轉換
        ClassicEditor
            .create(document.querySelector('#editor'));


        ////日期驗證
        //let strDate = document.getElementById("str_Date");
        //let spDate = document.getElementById("sp_date");

        //strDate.addEventListener("blur", () => {
        //    var dateArr = strDate.value.split("/");
        //    var dateNow = new Date();
        //    if (strDate.value == "") {
        //        spDate.innerHTML = "<img src='../../../img/error.png' />請輸入完整日期!!";
        //    }
        //    else {
        //        let year = dateArr[0];
        //        let month = dateArr[1];
        //        let day = dateArr[2];
        //        if (year <= dateNow.getFullYear()) {
        //            if (month >= 1 && month <= 12) {
        //                //小月
        //                if (month == 4 || month == 6 || month == 9 || month == 11) {
        //                    if (day > 0 && day <= 30) {
        //                        spDate.innerHTML = "<img src = '../../../img/correct.jpg' />格式正確"
        //                    }
        //                    else {
        //                        spDate.innerHTML = "<img src='../../../img/error.png' />日期有誤，請重新輸入日期"
        //                    }
        //                }
        //                //例外月(2月)
        //                else if (month == 2) {
        //                    //潤月
        //                    if ((year % 4) == 0) {
        //                        if (day > 0 && day <= 29) {
        //                            spDate.innerHTML = "<img src = '../../../img/correct.jpg' />格式正確"
        //                        }
        //                        else {
        //                            spDate.innerHTML = "<img src='../../../img/error.png' />日期有誤，請重新輸入日期"
        //                        }
        //                    }
        //                    else {
        //                        if (day > 0 && day <= 28) {
        //                            spDate.innerHTML = "<img src = '../../../img/correct.jpg' />格式正確"
        //                        }
        //                        else {
        //                            spDate.innerHTML = "<img src='../../../img/error.png' />日期有誤，請重新輸入日期"
        //                        }
        //                    }
        //                }
        //                //大月
        //                else {
        //                    if (day > 0 && day <= 31) {
        //                        spDate.innerHTML = "<img src = '../../../img/correct.jpg' />格式正確"
        //                    }
        //                    else {
        //                        spDate.innerHTML = "<img src='../../../img/error.png' />日期有誤，請重新輸入日期"
        //                    }
        //                }
        //            }
        //            else {
        //                spDate.innerHTML = "<img src='../../../img/error.png' />月份有誤，請重新輸入月份";
        //            }
        //        }
        //        else {
        //            spDate.innerHTML = "<img src='../../../img/error.png' />年份有誤，請重新輸入年份";
        //        }
        //    }
        //})
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medical/Areas/Admin/Views/ArticleAdmin/List.cshtml
@model IEnumerable<Medical.ViewModel.AArticleViewModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Admin_Layout.cshtml";
}


        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    @*修改*@
                    <h1 style="font-family: 微軟正黑體; font-weight: bold; color: darkorange;">衛教文章(後臺系統)</h1>
                </div>
                @*修改*@
            </div>
        </div>

        <div class="card">

            @using (Html.BeginForm())
            {
                //修改
            <div style="text-align: center;padding-top:20px">
                <label class="" style="font-size: 25px; font-family: 微軟正黑體; font-weight: bold; color: darkorange;">關鍵字 : </label>
                @Html.TextBox("txtKeyword", "", new { @class = "font-weight-bold", style = "font-size:26px;border-radius:15px;", @placeholder = "search..." })
                <button type="submit" class="btn bg-gradient-warning btn-lg">
                    <i class="fa fa-search">
                        查詢
                    </i>
                </button>
            </div>
                
            }
           
            @*修改*@
        <p  style="padding: 20px 30px 0 0; text-align: right;">
                @Html.ActionLink("新增衛教內容", "Create", "ArticleAdmin", "",
                                       new { @class = "btn btn-outline-success", @style = "font-size:18px;border-radius:5px; font-weight: bold " })
        </p>

            @{
                int count = 0;
                <div class="card">
                    <div class="card-header">
                        @*修改*@
                        <h3 class="card-title" style="font-size: 25px; font-family: 微軟正黑體; font-weight: bold; color: darkorange;">衛教表單細節</h3>
                    </div>

                    <div class="card-body">
                        <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                                        <thead>
                                            <tr>
                                                <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">序</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">發佈日期</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">醫生</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">疾病</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">文章內容</th>
                                                @*修改*@
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending"></th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                                count++;
                                                <tr class="odd">
                                                    <td class="dtr-control sorting_1 font-weight-bold" tabindex="0" style="width:5%">@count</td>
                                                    <td style="width:10%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.CreateDate)</td>
                                                    <td style="width:10%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.Doctor.DoctorName)</td>
                                                    <td style="width:15%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.Articeltitle)</td>
                                                    <td style="width:50%" class="font-weight-bold">@Html.DisplayFor(modelItem => item.ArticleContent)</td>
                                                    @*修改*@
                                                    <td style="width: 8%;" >
                                                        <div class="fas fa-pencil-alt" style="color: dodgerblue; margin-block: 3px">
                                                            @Html.ActionLink("修改", "Edit", "ArticleAdmin", new { id = item.ArticleId }, new { @class = "btn bg-gradient-primary btn-sm" })
                                                        </div>
                                                        <br />
                                                        <div class="fas fa-trash" style="color: orangered; margin-top: 3px">
                                                            @Html.ActionLink("刪除", "Delete", "ArticleAdmin", new { id = item.ArticleId },
new { onclick = "return confirm('確定要刪除此筆資料嗎??')", @class = "btn btn-danger btn-sm",@style= "margin-left:1px" })
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>

                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            }

</div>